language: node_js
node_js:
  - 8
script:
  - npm install
  - npm run build
before_deploy:
  - npm run package
deploy:
  provider: releases
  api_key:
    secure: Xg3Ju8R9VaZYChPkoz/MVij/RH0/6vSEc1I0SbxwhrVSIO8K01QXFPwKk+AF+eAl5qsNnDZgdS63h+6v4AUG9EMpP15NnI/+FPNeYjnBAB5TSXjvNGdcFLn3E4q4GpIFq4hoI1n7PjPYgJIosWGI3OdO7XO1H0o16+xmWWWGCYaqOrMNvUg2pqSdAkrzqAyeuIQ2rk5Uce4E3545DzgI5UcRkVkD3KRBfgdbwBkAMpfG6RbkG8jbjrYjoD3DsjkuZQscOgSj1o2z3HvcFJkChSvEfxMUnn0tyIrwxzcrBhne7Rzqe/SQg/Wwj5F4dv1qN7XCRJsqOFC80ggYWqSeoin8ajFm6XINaw6h5OgsybIEUsrmJxMYkbwGxkRxsLNJ8WOq9hDHaBNy34y8woIWO3rD7VLHcUUd/OCZ9t2/ZlfkcCsFcFaq3LDwV52hCiawSA9IEMAIhbvTcfZ/iySz3bspvlG/MofBIKV7eYdd2OAyWh26vgsA9d0MYUf/wKVlFT83qHXNNUOl8KspUGEb3RG7zKhCLQn8iiEYRqrdMJmULDx1wy3oRooZPi7Br/hhJtMxMoHXU8q+lgTrQzdmBTJ3a/yb6So8CzQ01r8tbykBVhR89AAfQb/MGaNZIDgMBmHDQGPl296qqCVZZnleKDoZQffjt/8VsoskL7u6DwM=
  file: addon.xpi
  skip_cleanup: true
  on:
    repo: mozilla/speaktome
    tags: true
    branch: master
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: SRw2L4bgz+ZyGVe397/SIse4Og4E2V7ov3xofXVsDLLhz7ovD5+aDKHz3nh2cKZSpqdyyXtcDuMIRKVpZvy40NDdGkRzB3yS1V79Cfl52jA+O+tUQVobfvj5RErNXDaUsL06tBnKLM86vk7i+aIvf8vZRk6ft9DkdSPoq+2z7KaNYcrXUpkwpXMG0LjGUZ6CY2v3rrFpYW5b8HGzYso6CSHBhc1xtm+Q/xjqXgXmf9sk2P37AEhPR/M+GVkaT0i73xxjDLHZEmEd53MbvltbERsInoOjWi4Ei/qjdzTg/v5PkLdceXGAUfaMF8BEh3v4HmgqCAfhZO6Am/9ZgWu8sPRillJoPxJdetdolfpVaSqpDwgJO539A0SUYETAsMFEmK9wQmRkNth5sly0rYRqRMJwaj0SbsX87+wZkSNi9Z3n5K6jjio6ANJ4+u06/RhLAqdlitOJOoFDUMwqkXencDcrrmbD6Y1kOBftgZrWW63yYYek+1KKEhaB60Nayw3kB/GgrAY5bj6i56zoRagd/BV5m6eN04hHKmTUcKzmo3PkglR45ToCbg+t9lMAc4pUv4gU1dOXEIbdoxjTC2oOV/al2Yn3hhLHWJcK7J2XNl7crPDneJhGPJIh3ErQ4mWI1pi2qos4Zq3aZH1bQDlNUibfEiC2mBsDNULLA+wEQ0U=
